name: build-documentation
on: 
  push:
    branches:
      - 'main'
    paths:
      - 'Sources/**'
jobs:
  build-docc:
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - uses: actions/cache@v3
        with:
          path: '.build'
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - uses: fwcd/swift-docc-action@v1.0.2
        with:
          target: CodeEditTextView
          output: ./docs
          hosting-base-path: CodeEditTextView
          disable-indexing: 'true'
          transform-for-static-hosting: 'true'
      - name: Init new repo in dist folder and commit generated files
        run: |
          cd docs
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
        
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs
          force: true
          directory: ./docs
