name: tests
on:
  push:
    branches:
      - 'main'
    paths:
      - 'Sources/**'
      - 'Tests/**'
  pull_request:
    branches:
      - 'main'
jobs:
  code-edit-text-view-tests:
    name: Testing CodeEditTextView
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - uses: actions/cache@v3
        with:
          path: '.build'
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Make executeable
        run: chmod +x ./.github/scripts/tests.sh
      - name: Testing Package
        run: exec ./.github/scripts/tests.sh
